import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedUsers() {
  await prisma.users.deleteMany();

  await prisma.users.createMany({
    data: [
      {
        username: "João",
        password: "j@oao123",
        email: "joao.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199001122",
        street: "Rua das Palmeiras",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01001000",
        gender: "Masculino",
        date_of_birth: "25/08/1985",
        languages: "Português, Inglês",
      },
      {
        username: "Ana",
        password: "an@1234",
        email: "ana.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199112233",
        street: "Avenida das Rosas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40020020",
        gender: "Feminino",
        date_of_birth: "15/07/1990",
        languages: "Português, Espanhol",
      },
      {
        username: "Lucas",
        password: "luc@1234",
        email: "lucas.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199445566",
        street: "Alameda dos Ipês",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Goiás",
        city: "Goiânia",
        postal_code: "74000000",
        gender: "Masculino",
        date_of_birth: "20/12/1988",
        languages: "Português, Inglês",
      },
      {
        username: "Mariana",
        password: "m@ri456",
        email: "mariana.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199223344",
        street: "Rua das Begônias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Alagoas",
        city: "Maceió",
        postal_code: "57010000",
        gender: "Feminino",
        date_of_birth: "10/10/1987",
        languages: "Português, Espanhol",
      },
      {
        username: "Thiago",
        password: "t$567",
        email: "thiago.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199889900",
        street: "Rua das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraíba",
        city: "João Pessoa",
        postal_code: "58010000",
        gender: "Masculino",
        date_of_birth: "15/05/1991",
        languages: "Português, Inglês",
      },
      {
        username: "Carla",
        password: "c@rl@123",
        email: "carla.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199556677",
        street: "Avenida das Margaridas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30110000",
        gender: "Feminino",
        date_of_birth: "22/11/1992",
        languages: "Português, Espanhol",
      },
      {
        username: "Roberto",
        password: "r0b3rt0#",
        email: "roberto.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199778899",
        street: "Alameda dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraná",
        city: "Curitiba",
        postal_code: "80010000",
        gender: "Masculino",
        date_of_birth: "18/04/1990",
        languages: "Português, Inglês",
      },
      {
        username: "Tatiana",
        password: "t@t1@n@",
        email: "tatiana.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199110022",
        street: "Rua dos Lírios",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Ceará",
        city: "Fortaleza",
        postal_code: "60000000",
        gender: "Feminino",
        date_of_birth: "12/09/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Leonardo",
        password: "l30n@rd0",
        email: "leonardo.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199001122",
        street: "Avenida dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Espírito Santo",
        city: "Vitória",
        postal_code: "29000000",
        gender: "Masculino",
        date_of_birth: "30/01/1985",
        languages: "Português, Espanhol",
      },
      {
        username: "Sandra",
        password: "s@ndr@123",
        email: "sandra.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199887766",
        street: "Rua das Oliveiras",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Pará",
        city: "Belém",
        postal_code: "66000000",
        gender: "Feminino",
        date_of_birth: "10/11/1986",
        languages: "Português, Inglês",
      },
      {
        username: "Felipe",
        password: "f3l1p3@",
        email: "felipe.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199554433",
        street: "Avenida dos Jasmins",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Mato Grosso",
        city: "Cuiabá",
        postal_code: "78000000",
        gender: "Masculino",
        date_of_birth: "14/02/1984",
        languages: "Português, Espanhol",
      },
      {
        username: "Gabriela",
        password: "g@br13l@",
        email: "gabriela.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199112233",
        street: "Rua das Hortênsias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Rodrigo",
        password: "r0dr1g0@",
        email: "rodrigo.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Souza",
        password: "r0dr1g0@",
        email: "souzin.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Quavo",
        password: "r0dr1g0@",
        email: "quavo.silva@gmail.com",
        role_id: "665fdcce-8795-4cec-8c91-0ff1c47e5284",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },

      //passenger

      {
        username: "pedro",
        password: "j@oao123",
        email: "pedrotxt.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199001122",
        street: "Rua das Palmeiras",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01001000",
        gender: "Masculino",
        date_of_birth: "25/08/1985",
        languages: "Português, Inglês",
      },
      {
        username: "Ana costa",
        password: "an@1234",
        email: "anarickeman.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199112233",
        street: "Avenida das Rosas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40020020",
        gender: "Feminino",
        date_of_birth: "15/07/1990",
        languages: "Português, Espanhol",
      },
      {
        username: "Lucas almeida",
        password: "luc@1234",
        email: "almeidalucas02.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199445566",
        street: "Alameda dos Ipês",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Goiás",
        city: "Goiânia",
        postal_code: "74000000",
        gender: "Masculino",
        date_of_birth: "20/12/1988",
        languages: "Português, Inglês",
      },
      {
        username: "Mariana",
        password: "m@ri456",
        email: "mariana03.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199223344",
        street: "Rua das Begônias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Alagoas",
        city: "Maceió",
        postal_code: "57010000",
        gender: "Feminino",
        date_of_birth: "10/10/1987",
        languages: "Português, Espanhol",
      },
      {
        username: "Thiago rick",
        password: "t$567",
        email: "rocktiago05.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199889900",
        street: "Rua das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraíba",
        city: "João Pessoa",
        postal_code: "58010000",
        gender: "Masculino",
        date_of_birth: "15/05/1991",
        languages: "Português, Inglês",
      },
      {
        username: "Carla teste",
        password: "c@rl@123",
        email: "carlinha03.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199556677",
        street: "Avenida das Margaridas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30110000",
        gender: "Feminino",
        date_of_birth: "22/11/1992",
        languages: "Português, Espanhol",
      },
      {
        username: "Roberto",
        password: "r0b3rt0#",
        email: "dagobertoteste.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199778899",
        street: "Alameda dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraná",
        city: "Curitiba",
        postal_code: "80010000",
        gender: "Masculino",
        date_of_birth: "18/04/1990",
        languages: "Português, Inglês",
      },
      {
        username: "Tatiana hilary",
        password: "t@t1@n@",
        email: "riana.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199110022",
        street: "Rua dos Lírios",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Ceará",
        city: "Fortaleza",
        postal_code: "60000000",
        gender: "Feminino",
        date_of_birth: "12/09/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Leonardo",
        password: "l30n@rd0",
        email: "leonardopai.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199001122",
        street: "Avenida dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Espírito Santo",
        city: "Vitória",
        postal_code: "29000000",
        gender: "Masculino",
        date_of_birth: "30/01/1985",
        languages: "Português, Espanhol",
      },
      {
        username: "Sandra",
        password: "s@ndr@123",
        email: "sandraaa.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199887766",
        street: "Rua das Oliveiras",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Pará",
        city: "Belém",
        postal_code: "66000000",
        gender: "Feminino",
        date_of_birth: "10/11/1986",
        languages: "Português, Inglês",
      },
      {
        username: "Felipe",
        password: "f3l1p3@",
        email: "felipecostadesilva.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199554433",
        street: "Avenida dos Jasmins",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Mato Grosso",
        city: "Cuiabá",
        postal_code: "78000000",
        gender: "Masculino",
        date_of_birth: "14/02/1984",
        languages: "Português, Espanhol",
      },
      {
        username: "Gabriela",
        password: "g@br13l@",
        email: "gabrielarocketseat.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199112233",
        street: "Rua das Hortênsias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Rodrigo",
        password: "r0dr1g0@",
        email: "rodriguinhoooo.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Souza",
        password: "r0dr1g0@",
        email: "souzinhaaa.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Quavo",
        password: "r0dr1g0@",
        email: "quavooo.silva@gmail.com",
        role_id: "8659bc51-fbef-42e7-a0c5-39fe219d2e27",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Br",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Carlos",
        password: "87654321",
        email: "carlos.silva1@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199776655",
        street: "Avenida das Gaivotas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio Grande do Sul",
        city: "Porto Alegre",
        postal_code: "90010120",
        gender: "Masculino",
        date_of_birth: "20/03/1992",
        languages: "Português, Inglês, Francês",
      },
      {
        username: "Caroline",
        password: "car0l1n3#",
        email: "caroline.silva2@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199334455",
        street: "Alameda dos Ipês",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Santa Catarina",
        city: "Florianópolis",
        postal_code: "88000000",
        gender: "Feminino",
        date_of_birth: "15/09/1986",
        languages: "Português, Inglês",
      },
      {
        username: "Fernando",
        password: "f3rn@nd0#",
        email: "fernando.silva3@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199887766",
        street: "Rua das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio Grande do Norte",
        city: "Natal",
        postal_code: "59000000",
        gender: "Masculino",
        date_of_birth: "20/06/1985",
        languages: "Português, Inglês",
      },
      {
        username: "Patrícia",
        password: "p@tr1c1@",
        email: "patricia.silva4@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199001122",
        street: "Rua das Violetas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Pernambuco",
        city: "Recife",
        postal_code: "50000000",
        gender: "Feminino",
        date_of_birth: "25/04/1984",
        languages: "Português, Espanhol",
      },
      {
        username: "Ricardo",
        password: "r1c@rd0",
        email: "ricardo.silva5@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199112233",
        street: "Avenida das Acácias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Maranhão",
        city: "São Luís",
        postal_code: "65000000",
        gender: "Masculino",
        date_of_birth: "10/11/1983",
        languages: "Português, Inglês",
      },
      {
        username: "Aline",
        password: "@l1n3#",
        email: "aline.silva6@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199445566",
        street: "Rua dos Crisântemos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraíba",
        city: "João Pessoa",
        postal_code: "58000000",
        gender: "Feminino",
        date_of_birth: "15/02/1982",
        languages: "Português, Inglês",
      },
      {
        username: "Marcos",
        password: "m@rc0s#",
        email: "marcos.silva7@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199778899",
        street: "Alameda das Azaléias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40000000",
        gender: "Masculino",
        date_of_birth: "20/05/1981",
        languages: "Português, Espanhol",
      },
      {
        username: "Camila",
        password: "c@m1l@",
        email: "camila.silva8@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199223344",
        street: "Rua das Magnólias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Goiás",
        city: "Goiânia",
        postal_code: "74000000",
        gender: "Feminino",
        date_of_birth: "10/07/1980",
        languages: "Português, Inglês",
      },
      {
        username: "Henrique",
        password: "h3nr1qu3#",
        email: "henrique.silva9@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199334455",
        street: "Avenida dos Crisântemos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30100000",
        gender: "Masculino",
        date_of_birth: "05/09/1979",
        languages: "Português, Espanhol",
      },
      {
        username: "Márcia",
        password: "m@rc1@",
        email: "marcia.silva10@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199887766",
        street: "Rua das Begônias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraná",
        city: "Curitiba",
        postal_code: "80000000",
        gender: "Feminino",
        date_of_birth: "22/03/1978",
        languages: "Português, Inglês",
      },
      {
        username: "Luciano",
        password: "luc14n0",
        email: "luciano.silva11@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199001122",
        street: "Alameda das Margaridas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Piauí",
        city: "Teresina",
        postal_code: "64000000",
        gender: "Masculino",
        date_of_birth: "18/02/1977",
        languages: "Português, Inglês",
      },
      {
        username: "Vanessa",
        password: "v@ness@",
        email: "vanessa.silva12@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199112233",
        street: "Rua das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Sergipe",
        city: "Aracaju",
        postal_code: "49000000",
        gender: "Feminino",
        date_of_birth: "30/01/1976",
        languages: "Português, Espanhol",
      },
      {
        username: "Gustavo",
        password: "gust@v0#",
        email: "gustavo.silva13@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199445566",
        street: "Alameda das Margaridas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Distrito Federal",
        city: "Brasília",
        postal_code: "70000000",
        gender: "Masculino",
        date_of_birth: "25/12/1975",
        languages: "Português, Inglês",
      },
      {
        username: "Mariana",
        password: "m@r1@n@",
        email: "mariana.silva14@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199778899",
        street: "Rua das Acácias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Espírito Santo",
        city: "Vitória",
        postal_code: "29000000",
        gender: "Feminino",
        date_of_birth: "10/08/1974",
        languages: "Português, Inglês",
      },
      {
        username: "Felipe",
        password: "f3l1p3#",
        email: "felipe.silva15@gmail.com",
        role_id: "b7df9f50-0b5c-45f9-ae54-5c37de8c97ae",
        phone: "55 1199223344",
        street: "Avenida das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        postal_code: "20000000",
        gender: "Masculino",
        date_of_birth: "05/06/1973",
        languages: "Português, Espanhol",
      },

      {
        username: "Gabriela",
        password: "g@br13l@",
        email: "gabriela.silva16@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199112233",
        street: "Rua das Hortênsias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Feminino",
        date_of_birth: "10/05/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Rodrigo",
        password: "r0dr1g0@",
        email: "rodrigo.silva17@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        postal_code: "20050010",
        gender: "Masculino",
        date_of_birth: "15/09/1986",
        languages: "Português, Espanhol",
      },
      {
        username: "Camila",
        password: "c@m1l@!",
        email: "camila.silva18@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199334455",
        street: "Rua das Magnólias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30120000",
        gender: "Feminino",
        date_of_birth: "20/07/1990",
        languages: "Português, Inglês",
      },
      {
        username: "Rafaela",
        password: "rafa3l@",
        email: "rafaela.silva19@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199445566",
        street: "Avenida das Rosas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40020020",
        gender: "Feminino",
        date_of_birth: "25/03/1985",
        languages: "Português, Francês",
      },
      {
        username: "Fernando",
        password: "f3rn@nd0#",
        email: "fernando.silva20@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199556677",
        street: "Rua dos Girassóis",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Santa Catarina",
        city: "Florianópolis",
        postal_code: "88025000",
        gender: "Masculino",
        date_of_birth: "10/11/1983",
        languages: "Português, Inglês",
      },
      {
        username: "Luana",
        password: "l@n4l1u$",
        email: "luana.silva21@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199667788",
        street: "Avenida das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Goiás",
        city: "Goiânia",
        postal_code: "74010010",
        gender: "Feminino",
        date_of_birth: "05/12/1992",
        languages: "Português, Espanhol",
      },
      {
        username: "Marcos",
        password: "m@rc05#",
        email: "marcos.silva22@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199778899",
        street: "Rua das Tulipas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Paraná",
        city: "Curitiba",
        postal_code: "80020000",
        gender: "Masculino",
        date_of_birth: "15/04/1987",
        languages: "Português, Inglês",
      },
      {
        username: "Amanda",
        password: "4m4nd@*",
        email: "amanda.silva23@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199889900",
        street: "Rua das Camélias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Ceará",
        city: "Fortaleza",
        postal_code: "60010000",
        gender: "Feminino",
        date_of_birth: "20/02/1995",
        languages: "Português, Inglês",
      },
      {
        username: "Renato",
        password: "r3n@t0&",
        email: "renato.silva24@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199112233",
        street: "Avenida dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Espírito Santo",
        city: "Vitória",
        postal_code: "29010000",
        gender: "Masculino",
        date_of_birth: "10/10/1989",
        languages: "Português, Espanhol",
      },
      {
        username: "Laura",
        password: "l@ur@!",
        email: "laura.silva25@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199223344",
        street: "Rua das Violetas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio Grande do Sul",
        city: "Porto Alegre",
        postal_code: "90020020",
        gender: "Feminino",
        date_of_birth: "15/05/1993",
        languages: "Português, Inglês",
      },
      {
        username: "Pedro",
        password: "p3dr0#",
        email: "pedro.silva26@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199445566",
        street: "Avenida dos Lírios",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Amazonas",
        city: "Manaus",
        postal_code: "69010000",
        gender: "Masculino",
        date_of_birth: "20/06/1986",
        languages: "Português, Espanhol",
      },
      {
        username: "Matheus",
        password: "m@th3u$",
        email: "matheus.silva27@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199667788",
        street: "Avenida das Bromélias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Mato Grosso do Sul",
        city: "Campo Grande",
        postal_code: "79010000",
        gender: "Masculino",
        date_of_birth: "12/12/1988",
        languages: "Português, Inglês",
      },

      {
        username: "Renan",
        password: "r3n@n*",
        email: "renan.silva29@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199778899",
        street: "Rua dos Crisântemos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Pará",
        city: "Belém",
        postal_code: "66010000",
        gender: "Masculino",
        date_of_birth: "25/09/1984",
        languages: "Português, Inglês",
      },

      {
        username: "Beatriz",
        password: "b34tr1z*",
        email: "beatriz.silva30@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199889900",
        street: "Avenida das Margaridas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio Grande do Norte",
        city: "Natal",
        postal_code: "59010000",
        gender: "Feminino",
        date_of_birth: "10/11/1991",
        languages: "Português, Espanhol",
      },
      {
        username: "Gabriel",
        password: "g@br13l*",
        email: "gabriel.silva31@gmail.com",
        role_id: "477b3243-8a2e-484f-baf2-18bf7f08aa31",
        phone: "55 1199556677",
        street: "Rua das Acácias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Alagoas",
        city: "Maceió",
        postal_code: "57010000",
        gender: "Masculino",
        date_of_birth: "05/07/1994",
        languages: "Português, Inglês",
      },

      {
        username: "André",
        password: "4ndr3*",
        email: "andre.silva32@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199112233",
        street: "Rua das Violetas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01002000",
        gender: "Masculino",
        date_of_birth: "15/09/1986",
        languages: "Português, Espanhol",
      },
      {
        username: "Larissa",
        password: "l@r1ss@*",
        email: "larissa.silva33@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199223344",
        street: "Avenida dos Jardins",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        postal_code: "20050010",
        gender: "Feminino",
        date_of_birth: "25/03/1985",
        languages: "Português, Francês",
      },
      {
        username: "Thiago",
        password: "th14g0*",
        email: "thiago.silva34@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199556677",
        street: "Rua das Rosas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30120000",
        gender: "Masculino",
        date_of_birth: "10/11/1987",
        languages: "Português, Inglês",
      },
      {
        username: "Juliana",
        password: "jul14n@*",
        email: "juliana.silva35@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199667788",
        street: "Rua das Magnólias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01003000",
        gender: "Feminino",
        date_of_birth: "08/07/1986",
        languages: "Português, Inglês",
      },
      {
        username: "Gabriel",
        password: "g@br13l*",
        email: "gabriel.silva36@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199778899",
        street: "Rua dos Lírios",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30121000",
        gender: "Masculino",
        date_of_birth: "14/02/1988",
        languages: "Português, Espanhol",
      },
      {
        username: "Ana",
        password: "4n@*",
        email: "ana.silva37@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199889900",
        street: "Avenida das Camélias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40010000",
        gender: "Feminino",
        date_of_birth: "22/11/1990",
        languages: "Português, Inglês",
      },
      {
        username: "Renato",
        password: "r3n@t0*",
        email: "renato.silva38@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199445566",
        street: "Rua das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Ceará",
        city: "Fortaleza",
        postal_code: "60020000",
        gender: "Masculino",
        date_of_birth: "20/02/1991",
        languages: "Português, Espanhol",
      },
      {
        username: "Isabela",
        password: "1s@b3l@*",
        email: "isabela.silva39@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199112233",
        street: "Avenida dos Cravos",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Espírito Santo",
        city: "Vitória",
        postal_code: "29010000",
        gender: "Feminino",
        date_of_birth: "10/10/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Diego",
        password: "d13g0*",
        email: "diego.silva40@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199223344",
        street: "Rua dos Girassóis",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Santa Catarina",
        city: "Florianópolis",
        postal_code: "88025000",
        gender: "Masculino",
        date_of_birth: "12/12/1987",
        languages: "Português, Espanhol",
      },
      {
        username: "Mariana",
        password: "m@r1@n@*",
        email: "mariana.silva41@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199556677",
        street: "Alameda das Orquídeas",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Goiás",
        city: "Goiânia",
        postal_code: "74010000",
        gender: "Feminino",
        date_of_birth: "05/12/1992",
        languages: "Português, Espanhol",
      },
      {
        username: "Lucas",
        password: "luc@s*",
        email: "lucas.silva42@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199667788",
        street: "Rua das Acácias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "São Paulo",
        city: "São Paulo",
        postal_code: "01004000",
        gender: "Masculino",
        date_of_birth: "30/01/1989",
        languages: "Português, Inglês",
      },
      {
        username: "Carla",
        password: "c@rl@*",
        email: "carla.silva43@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199778899",
        street: "Rua dos Ipês",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30121000",
        gender: "Feminino",
        date_of_birth: "18/08/1994",
        languages: "Português, Espanhol",
      },

      {
        username: "Rafael",
        password: "r@f43l*",
        email: "rafael.silva45@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199445566",
        street: "Rua das Hortênsias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Santa Catarina",
        city: "Florianópolis",
        postal_code: "88035000",
        gender: "Masculino",
        date_of_birth: "22/05/1995",
        languages: "Português, Inglês",
      },
      {
        username: "Camila",
        password: "c@m1l@*",
        email: "camila.silva46@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199112233",
        street: "Rua das Bromélias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Bahia",
        city: "Salvador",
        postal_code: "40020000",
        gender: "Feminino",
        date_of_birth: "17/07/1996",
        languages: "Português, Espanhol",
      },
      {
        username: "Vinícius",
        password: "v1n1c1us*",
        email: "vinicius.silva47@gmail.com",
        role_id: "faf787c0-6b97-4dae-84e4-ca947c790bf2",
        phone: "55 1199223344",
        street: "Rua das Glicínias",
        country: "Brasil",
        nationality: "Brasileira",
        state: "Minas Gerais",
        city: "Belo Horizonte",
        postal_code: "30122000",
        gender: "Masculino",
        date_of_birth: "25/04/1997",
        languages: "Português, Inglês",
      },
    ],
  });
}

seedUsers()
  .then(async () => {
    console.log("Users seeded successfully");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
